/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CvGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.Cv.Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCvKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cNameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cNameAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cNameSTRINGTerminalRuleCall_4_0 = (RuleCall)cNameAssignment_4.eContents().get(0);
		private final Keyword cTitleKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cTitleAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cTitleSTRINGTerminalRuleCall_7_0 = (RuleCall)cTitleAssignment_7.eContents().get(0);
		private final Keyword cAboutKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cAboutAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cAboutSTRINGTerminalRuleCall_10_0 = (RuleCall)cAboutAssignment_10.eContents().get(0);
		private final Keyword cEducationKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cColonKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cEducationAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cEducationEducationParserRuleCall_13_0 = (RuleCall)cEducationAssignment_13.eContents().get(0);
		private final Keyword cExperienceKeyword_14 = (Keyword)cGroup.eContents().get(14);
		private final Keyword cColonKeyword_15 = (Keyword)cGroup.eContents().get(15);
		private final Assignment cExperienceAssignment_16 = (Assignment)cGroup.eContents().get(16);
		private final RuleCall cExperienceExperienceParserRuleCall_16_0 = (RuleCall)cExperienceAssignment_16.eContents().get(0);
		private final Keyword cContactKeyword_17 = (Keyword)cGroup.eContents().get(17);
		private final Keyword cColonKeyword_18 = (Keyword)cGroup.eContents().get(18);
		private final Assignment cContactAssignment_19 = (Assignment)cGroup.eContents().get(19);
		private final RuleCall cContactSTRINGTerminalRuleCall_19_0 = (RuleCall)cContactAssignment_19.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_20 = (Keyword)cGroup.eContents().get(20);
		
		//Model:
		//    'cv' '{'
		//        'name' ':' name=STRING
		//        'title' ':' title=STRING
		//        'about' ':' about=STRING
		//        'education' ':' education+=Education*
		//        'experience' ':' experience+=Experience*
		//        'contact' ':' contact=STRING
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'cv' '{'
		//    'name' ':' name=STRING
		//    'title' ':' title=STRING
		//    'about' ':' about=STRING
		//    'education' ':' education+=Education*
		//    'experience' ':' experience+=Experience*
		//    'contact' ':' contact=STRING
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'cv'
		public Keyword getCvKeyword_0() { return cCvKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'name'
		public Keyword getNameKeyword_2() { return cNameKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//name=STRING
		public Assignment getNameAssignment_4() { return cNameAssignment_4; }
		
		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_4_0() { return cNameSTRINGTerminalRuleCall_4_0; }
		
		//'title'
		public Keyword getTitleKeyword_5() { return cTitleKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//title=STRING
		public Assignment getTitleAssignment_7() { return cTitleAssignment_7; }
		
		//STRING
		public RuleCall getTitleSTRINGTerminalRuleCall_7_0() { return cTitleSTRINGTerminalRuleCall_7_0; }
		
		//'about'
		public Keyword getAboutKeyword_8() { return cAboutKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//about=STRING
		public Assignment getAboutAssignment_10() { return cAboutAssignment_10; }
		
		//STRING
		public RuleCall getAboutSTRINGTerminalRuleCall_10_0() { return cAboutSTRINGTerminalRuleCall_10_0; }
		
		//'education'
		public Keyword getEducationKeyword_11() { return cEducationKeyword_11; }
		
		//':'
		public Keyword getColonKeyword_12() { return cColonKeyword_12; }
		
		//education+=Education*
		public Assignment getEducationAssignment_13() { return cEducationAssignment_13; }
		
		//Education
		public RuleCall getEducationEducationParserRuleCall_13_0() { return cEducationEducationParserRuleCall_13_0; }
		
		//'experience'
		public Keyword getExperienceKeyword_14() { return cExperienceKeyword_14; }
		
		//':'
		public Keyword getColonKeyword_15() { return cColonKeyword_15; }
		
		//experience+=Experience*
		public Assignment getExperienceAssignment_16() { return cExperienceAssignment_16; }
		
		//Experience
		public RuleCall getExperienceExperienceParserRuleCall_16_0() { return cExperienceExperienceParserRuleCall_16_0; }
		
		//'contact'
		public Keyword getContactKeyword_17() { return cContactKeyword_17; }
		
		//':'
		public Keyword getColonKeyword_18() { return cColonKeyword_18; }
		
		//contact=STRING
		public Assignment getContactAssignment_19() { return cContactAssignment_19; }
		
		//STRING
		public RuleCall getContactSTRINGTerminalRuleCall_19_0() { return cContactSTRINGTerminalRuleCall_19_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_20() { return cRightCurlyBracketKeyword_20; }
	}
	public class EducationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.Cv.Education");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEduKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDegreeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDegreeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDegreeSTRINGTerminalRuleCall_4_0 = (RuleCall)cDegreeAssignment_4.eContents().get(0);
		private final Keyword cUniversityKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cUniversityAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cUniversitySTRINGTerminalRuleCall_7_0 = (RuleCall)cUniversityAssignment_7.eContents().get(0);
		private final Keyword cYearKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cYearAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cYearINTTerminalRuleCall_10_0 = (RuleCall)cYearAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Education:
		//    'edu' '{'
		//        'degree' ':' degree=STRING
		//        'university' ':' university=STRING
		//        'year' ':' year=INT
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'edu' '{'
		//    'degree' ':' degree=STRING
		//    'university' ':' university=STRING
		//    'year' ':' year=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'edu'
		public Keyword getEduKeyword_0() { return cEduKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'degree'
		public Keyword getDegreeKeyword_2() { return cDegreeKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//degree=STRING
		public Assignment getDegreeAssignment_4() { return cDegreeAssignment_4; }
		
		//STRING
		public RuleCall getDegreeSTRINGTerminalRuleCall_4_0() { return cDegreeSTRINGTerminalRuleCall_4_0; }
		
		//'university'
		public Keyword getUniversityKeyword_5() { return cUniversityKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//university=STRING
		public Assignment getUniversityAssignment_7() { return cUniversityAssignment_7; }
		
		//STRING
		public RuleCall getUniversitySTRINGTerminalRuleCall_7_0() { return cUniversitySTRINGTerminalRuleCall_7_0; }
		
		//'year'
		public Keyword getYearKeyword_8() { return cYearKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//year=INT
		public Assignment getYearAssignment_10() { return cYearAssignment_10; }
		
		//INT
		public RuleCall getYearINTTerminalRuleCall_10_0() { return cYearINTTerminalRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class ExperienceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.Cv.Experience");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExpKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cPositionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPositionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPositionSTRINGTerminalRuleCall_4_0 = (RuleCall)cPositionAssignment_4.eContents().get(0);
		private final Keyword cCompanyKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cColonKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cCompanyAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cCompanySTRINGTerminalRuleCall_7_0 = (RuleCall)cCompanyAssignment_7.eContents().get(0);
		private final Keyword cYearKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cColonKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cYearAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cYearINTTerminalRuleCall_10_0 = (RuleCall)cYearAssignment_10.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Experience:
		//    'exp' '{'
		//        'position' ':' position=STRING
		//        'company' ':' company=STRING
		//        'year' ':' year=INT
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'exp' '{'
		//    'position' ':' position=STRING
		//    'company' ':' company=STRING
		//    'year' ':' year=INT
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'exp'
		public Keyword getExpKeyword_0() { return cExpKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'position'
		public Keyword getPositionKeyword_2() { return cPositionKeyword_2; }
		
		//':'
		public Keyword getColonKeyword_3() { return cColonKeyword_3; }
		
		//position=STRING
		public Assignment getPositionAssignment_4() { return cPositionAssignment_4; }
		
		//STRING
		public RuleCall getPositionSTRINGTerminalRuleCall_4_0() { return cPositionSTRINGTerminalRuleCall_4_0; }
		
		//'company'
		public Keyword getCompanyKeyword_5() { return cCompanyKeyword_5; }
		
		//':'
		public Keyword getColonKeyword_6() { return cColonKeyword_6; }
		
		//company=STRING
		public Assignment getCompanyAssignment_7() { return cCompanyAssignment_7; }
		
		//STRING
		public RuleCall getCompanySTRINGTerminalRuleCall_7_0() { return cCompanySTRINGTerminalRuleCall_7_0; }
		
		//'year'
		public Keyword getYearKeyword_8() { return cYearKeyword_8; }
		
		//':'
		public Keyword getColonKeyword_9() { return cColonKeyword_9; }
		
		//year=INT
		public Assignment getYearAssignment_10() { return cYearAssignment_10; }
		
		//INT
		public RuleCall getYearINTTerminalRuleCall_10_0() { return cYearINTTerminalRuleCall_10_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	
	
	private final ModelElements pModel;
	private final EducationElements pEducation;
	private final ExperienceElements pExperience;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CvGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pEducation = new EducationElements();
		this.pExperience = new ExperienceElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.Cv".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    'cv' '{'
	//        'name' ':' name=STRING
	//        'title' ':' title=STRING
	//        'about' ':' about=STRING
	//        'education' ':' education+=Education*
	//        'experience' ':' experience+=Experience*
	//        'contact' ':' contact=STRING
	//    '}';
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//Education:
	//    'edu' '{'
	//        'degree' ':' degree=STRING
	//        'university' ':' university=STRING
	//        'year' ':' year=INT
	//    '}';
	public EducationElements getEducationAccess() {
		return pEducation;
	}
	
	public ParserRule getEducationRule() {
		return getEducationAccess().getRule();
	}
	
	//Experience:
	//    'exp' '{'
	//        'position' ':' position=STRING
	//        'company' ':' company=STRING
	//        'year' ':' year=INT
	//    '}';
	public ExperienceElements getExperienceAccess() {
		return pExperience;
	}
	
	public ParserRule getExperienceRule() {
		return getExperienceAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
