/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.cv.ui.internal.CvActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CvExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CvActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CvActivator activator = CvActivator.getInstance();
		return activator != null ? activator.getInjector(CvActivator.ORG_XTEXT_EXAMPLE_CV) : null;
	}

}
