/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.cv.ui.internal.CvActivator;

public class CvUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CvActivator.getInstance().getInjector("org.xtext.example.Cv");
	}

}
