/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.CvRuntimeModule;
import org.xtext.example.CvStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class CvIdeSetup extends CvStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new CvRuntimeModule(), new CvIdeModule()));
	}
	
}
