/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cv;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.cv.CvFactory
 * @model kind="package"
 * @generated
 */
public interface CvPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cv";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/Cv";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cv";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CvPackage eINSTANCE = org.xtext.example.cv.impl.CvPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.cv.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cv.impl.ModelImpl
   * @see org.xtext.example.cv.impl.CvPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__TITLE = 1;

  /**
   * The feature id for the '<em><b>About</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ABOUT = 2;

  /**
   * The feature id for the '<em><b>Education</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__EDUCATION = 3;

  /**
   * The feature id for the '<em><b>Experience</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__EXPERIENCE = 4;

  /**
   * The feature id for the '<em><b>Contact</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__CONTACT = 5;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 6;

  /**
   * The meta object id for the '{@link org.xtext.example.cv.impl.EducationImpl <em>Education</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cv.impl.EducationImpl
   * @see org.xtext.example.cv.impl.CvPackageImpl#getEducation()
   * @generated
   */
  int EDUCATION = 1;

  /**
   * The feature id for the '<em><b>Degree</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDUCATION__DEGREE = 0;

  /**
   * The feature id for the '<em><b>University</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDUCATION__UNIVERSITY = 1;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDUCATION__YEAR = 2;

  /**
   * The number of structural features of the '<em>Education</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EDUCATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.cv.impl.ExperienceImpl <em>Experience</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.cv.impl.ExperienceImpl
   * @see org.xtext.example.cv.impl.CvPackageImpl#getExperience()
   * @generated
   */
  int EXPERIENCE = 2;

  /**
   * The feature id for the '<em><b>Position</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIENCE__POSITION = 0;

  /**
   * The feature id for the '<em><b>Company</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIENCE__COMPANY = 1;

  /**
   * The feature id for the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIENCE__YEAR = 2;

  /**
   * The number of structural features of the '<em>Experience</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPERIENCE_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.cv.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.cv.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.cv.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Model#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Title</em>'.
   * @see org.xtext.example.cv.Model#getTitle()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Title();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Model#getAbout <em>About</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>About</em>'.
   * @see org.xtext.example.cv.Model#getAbout()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_About();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cv.Model#getEducation <em>Education</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Education</em>'.
   * @see org.xtext.example.cv.Model#getEducation()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Education();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.cv.Model#getExperience <em>Experience</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Experience</em>'.
   * @see org.xtext.example.cv.Model#getExperience()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Experience();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Model#getContact <em>Contact</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Contact</em>'.
   * @see org.xtext.example.cv.Model#getContact()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Contact();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cv.Education <em>Education</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Education</em>'.
   * @see org.xtext.example.cv.Education
   * @generated
   */
  EClass getEducation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Education#getDegree <em>Degree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degree</em>'.
   * @see org.xtext.example.cv.Education#getDegree()
   * @see #getEducation()
   * @generated
   */
  EAttribute getEducation_Degree();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Education#getUniversity <em>University</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>University</em>'.
   * @see org.xtext.example.cv.Education#getUniversity()
   * @see #getEducation()
   * @generated
   */
  EAttribute getEducation_University();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Education#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.example.cv.Education#getYear()
   * @see #getEducation()
   * @generated
   */
  EAttribute getEducation_Year();

  /**
   * Returns the meta object for class '{@link org.xtext.example.cv.Experience <em>Experience</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Experience</em>'.
   * @see org.xtext.example.cv.Experience
   * @generated
   */
  EClass getExperience();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Experience#getPosition <em>Position</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Position</em>'.
   * @see org.xtext.example.cv.Experience#getPosition()
   * @see #getExperience()
   * @generated
   */
  EAttribute getExperience_Position();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Experience#getCompany <em>Company</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Company</em>'.
   * @see org.xtext.example.cv.Experience#getCompany()
   * @see #getExperience()
   * @generated
   */
  EAttribute getExperience_Company();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.cv.Experience#getYear <em>Year</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Year</em>'.
   * @see org.xtext.example.cv.Experience#getYear()
   * @see #getExperience()
   * @generated
   */
  EAttribute getExperience_Year();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CvFactory getCvFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.cv.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cv.impl.ModelImpl
     * @see org.xtext.example.cv.impl.CvPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__TITLE = eINSTANCE.getModel_Title();

    /**
     * The meta object literal for the '<em><b>About</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__ABOUT = eINSTANCE.getModel_About();

    /**
     * The meta object literal for the '<em><b>Education</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__EDUCATION = eINSTANCE.getModel_Education();

    /**
     * The meta object literal for the '<em><b>Experience</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__EXPERIENCE = eINSTANCE.getModel_Experience();

    /**
     * The meta object literal for the '<em><b>Contact</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__CONTACT = eINSTANCE.getModel_Contact();

    /**
     * The meta object literal for the '{@link org.xtext.example.cv.impl.EducationImpl <em>Education</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cv.impl.EducationImpl
     * @see org.xtext.example.cv.impl.CvPackageImpl#getEducation()
     * @generated
     */
    EClass EDUCATION = eINSTANCE.getEducation();

    /**
     * The meta object literal for the '<em><b>Degree</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDUCATION__DEGREE = eINSTANCE.getEducation_Degree();

    /**
     * The meta object literal for the '<em><b>University</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDUCATION__UNIVERSITY = eINSTANCE.getEducation_University();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EDUCATION__YEAR = eINSTANCE.getEducation_Year();

    /**
     * The meta object literal for the '{@link org.xtext.example.cv.impl.ExperienceImpl <em>Experience</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.cv.impl.ExperienceImpl
     * @see org.xtext.example.cv.impl.CvPackageImpl#getExperience()
     * @generated
     */
    EClass EXPERIENCE = eINSTANCE.getExperience();

    /**
     * The meta object literal for the '<em><b>Position</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPERIENCE__POSITION = eINSTANCE.getExperience_Position();

    /**
     * The meta object literal for the '<em><b>Company</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPERIENCE__COMPANY = eINSTANCE.getExperience_Company();

    /**
     * The meta object literal for the '<em><b>Year</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXPERIENCE__YEAR = eINSTANCE.getExperience_Year();

  }

} //CvPackage
