/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cv;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Education</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cv.Education#getDegree <em>Degree</em>}</li>
 *   <li>{@link org.xtext.example.cv.Education#getUniversity <em>University</em>}</li>
 *   <li>{@link org.xtext.example.cv.Education#getYear <em>Year</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cv.CvPackage#getEducation()
 * @model
 * @generated
 */
public interface Education extends EObject
{
  /**
   * Returns the value of the '<em><b>Degree</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Degree</em>' attribute.
   * @see #setDegree(String)
   * @see org.xtext.example.cv.CvPackage#getEducation_Degree()
   * @model
   * @generated
   */
  String getDegree();

  /**
   * Sets the value of the '{@link org.xtext.example.cv.Education#getDegree <em>Degree</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Degree</em>' attribute.
   * @see #getDegree()
   * @generated
   */
  void setDegree(String value);

  /**
   * Returns the value of the '<em><b>University</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>University</em>' attribute.
   * @see #setUniversity(String)
   * @see org.xtext.example.cv.CvPackage#getEducation_University()
   * @model
   * @generated
   */
  String getUniversity();

  /**
   * Sets the value of the '{@link org.xtext.example.cv.Education#getUniversity <em>University</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>University</em>' attribute.
   * @see #getUniversity()
   * @generated
   */
  void setUniversity(String value);

  /**
   * Returns the value of the '<em><b>Year</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Year</em>' attribute.
   * @see #setYear(int)
   * @see org.xtext.example.cv.CvPackage#getEducation_Year()
   * @model
   * @generated
   */
  int getYear();

  /**
   * Sets the value of the '{@link org.xtext.example.cv.Education#getYear <em>Year</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Year</em>' attribute.
   * @see #getYear()
   * @generated
   */
  void setYear(int value);

} // Education
