/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.cv;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.cv.Model#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.cv.Model#getTitle <em>Title</em>}</li>
 *   <li>{@link org.xtext.example.cv.Model#getAbout <em>About</em>}</li>
 *   <li>{@link org.xtext.example.cv.Model#getEducation <em>Education</em>}</li>
 *   <li>{@link org.xtext.example.cv.Model#getExperience <em>Experience</em>}</li>
 *   <li>{@link org.xtext.example.cv.Model#getContact <em>Contact</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.cv.CvPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.cv.CvPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.cv.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Title</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title</em>' attribute.
   * @see #setTitle(String)
   * @see org.xtext.example.cv.CvPackage#getModel_Title()
   * @model
   * @generated
   */
  String getTitle();

  /**
   * Sets the value of the '{@link org.xtext.example.cv.Model#getTitle <em>Title</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title</em>' attribute.
   * @see #getTitle()
   * @generated
   */
  void setTitle(String value);

  /**
   * Returns the value of the '<em><b>About</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>About</em>' attribute.
   * @see #setAbout(String)
   * @see org.xtext.example.cv.CvPackage#getModel_About()
   * @model
   * @generated
   */
  String getAbout();

  /**
   * Sets the value of the '{@link org.xtext.example.cv.Model#getAbout <em>About</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>About</em>' attribute.
   * @see #getAbout()
   * @generated
   */
  void setAbout(String value);

  /**
   * Returns the value of the '<em><b>Education</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.cv.Education}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Education</em>' containment reference list.
   * @see org.xtext.example.cv.CvPackage#getModel_Education()
   * @model containment="true"
   * @generated
   */
  EList<Education> getEducation();

  /**
   * Returns the value of the '<em><b>Experience</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.cv.Experience}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Experience</em>' containment reference list.
   * @see org.xtext.example.cv.CvPackage#getModel_Experience()
   * @model containment="true"
   * @generated
   */
  EList<Experience> getExperience();

  /**
   * Returns the value of the '<em><b>Contact</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contact</em>' attribute.
   * @see #setContact(String)
   * @see org.xtext.example.cv.CvPackage#getModel_Contact()
   * @model
   * @generated
   */
  String getContact();

  /**
   * Sets the value of the '{@link org.xtext.example.cv.Model#getContact <em>Contact</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Contact</em>' attribute.
   * @see #getContact()
   * @generated
   */
  void setContact(String value);

} // Model
